version: "3.9"
services:
  app:
    image: dev-container-cpp-db2:alpha1
#    build:
#      context: ..
#      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace # Mount project files for development
    command: sleep infinity # Keeps the container running for dev use
    tty: true
    environment:
      - DB2_HOST=db2
      - DB2_PORT=50000
      - DB2_USER=db2inst1
      - DB2_PASSWORD=examplePwd # Replace with a secure password as appropriate
      - DB2_DATABASE=testdb
    depends_on:
      - db2
    ports:
      - "50051:50051" # Example gRPC port, adjust as needed

  db2:
    image: ibmcom/db2
    platform: linux/amd64
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=examplePwd
      - DBNAME=testdb
      - ARCHIVE_LOGS=false
    ports:
      - "50000:50000"
    healthcheck:
      test: ["CMD", "su", "-", "db2inst1", "-c", "db2 connect to testdb"]
      interval: 30s
      timeout: 10s
      retries: 20
